services:
  nevertable-web:
    image: nevertable:latest
    build:
      context: "."
      args:
        - "extra_extensions=xdebug"
    volumes:
      - "./data:/var/www/html/public/data"
    ports:
      - "8888:80"
    depends_on:
      - nevertable-db
    extra_hosts:
      - "host.docker.internal:host-gateway" # for xdebug
  nevertable-db:
    image: mariadb:10.10.2
    volumes:
      - "./install:/docker-entrypoint-initdb.d"
      - "data_db:/var/lib/mysql"
    environment:
      MARIADB_ROOT_HOST: localhost
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
  adminer:
    image: adminer
    ports:
      - "8081:8080"
volumes:
  data_db:
